### PR TITLE
added machine learning model along with dataset to predict laptop price

### PR DESCRIPTION
**Pull request by AkUp007**
Developed a laptop price predictor using advanced machine learning techniques, improving prediction accuracy by 9%. Leveraged feature engineering and model optimization on a dataset with 1303 features and 12 observations to create a reliable tool for consumers.

### CODE REVIEW

**Comment by Ryder-07** [comment]
kindly p[ut a proper description

**Comment by AkUp007** [comment]
Ok i will. Thanks for your consideration

**Comment by AkUp007** [comment]
can you unlock the PR so that i can edit and write the description?

**Comment by AkUp007** [comment]
Updated the description, kindly consider further processes.

**Pull request merged**
